CREATE TABLE IF NOT EXISTS acl_class (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS acl_sid (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal BOOLEAN NOT NULL,
    sid VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS acl_object_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id_class BIGINT NOT NULL,
    object_id_identity BIGINT NOT NULL,
    parent_object BIGINT,
    owner_sid BIGINT,
    entries_inheriting BOOLEAN NOT NULL,
    CONSTRAINT fk_acl_object_identity_parent FOREIGN KEY(parent_object) REFERENCES acl_object_identity(id),
    CONSTRAINT fk_acl_object_identity_class FOREIGN KEY(object_id_class) REFERENCES acl_class(id),
    CONSTRAINT fk_acl_object_identity_owner FOREIGN KEY(owner_sid) REFERENCES acl_sid(id),
    CONSTRAINT unique_uk_3 UNIQUE(object_id_class, object_id_identity)
);

CREATE TABLE IF NOT EXISTS acl_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acl_object_identity BIGINT NOT NULL,
    ace_order INT NOT NULL,
    sid BIGINT NOT NULL,
    mask INT NOT NULL,
    granting BOOLEAN NOT NULL,
    audit_success BOOLEAN NOT NULL,
    audit_failure BOOLEAN NOT NULL,
    CONSTRAINT fk_acl_entry_object FOREIGN KEY(acl_object_identity) REFERENCES acl_object_identity(id),
    CONSTRAINT fk_acl_entry_sid FOREIGN KEY(sid) REFERENCES acl_sid(id),
    CONSTRAINT unique_uk_4 UNIQUE(acl_object_identity, ace_order)
);

CREATE INDEX IF NOT EXISTS idx_acl_object_identity_parent ON acl_object_identity(parent_object);
CREATE INDEX IF NOT EXISTS idx_acl_object_identity_owner ON acl_object_identity(owner_sid);
CREATE INDEX IF NOT EXISTS idx_acl_entry_object ON acl_entry(acl_object_identity);
CREATE INDEX IF NOT EXISTS idx_acl_entry_sid ON acl_entry(sid);