CREATE TABLE IF NOT EXISTS users (
    id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255) not null unique,
    password varchar(255) not null,
    role varchar(255) not null default 'USER',
    enabled boolean default true
);

CREATE TABLE IF NOT EXISTS authors (
    id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(255)
);

CREATE TABLE IF NOT EXISTS genres (
    id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
);

CREATE TABLE IF NOT EXISTS books (
    id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255),
    author_id bigint references authors (id) on delete cascade,
    genre_id bigint references genres(id) on delete cascade
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar(1000) not null,
    book_id bigint references books (id) on delete cascade,
    user_id bigint REFERENCES users(id) ON delete set null
);